# Lab-01-1 Tensor Manipulation 1

## Broadcasting

In [1]:
import torch

In [2]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [3]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]])
print(m1 + m2)

tensor([[4., 5.]])


In [4]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## Matrix Multiplication vs. (Element-wise) Multiplication

In [5]:
m1 = torch.FloatTensor([[1, 2], 
                        [3, 4]])
m2 = torch.FloatTensor([[1], 
                        [2]])

In [6]:
m1.matmul(m2)

tensor([[ 5.],
        [11.]])

In [7]:
m1 * m2

tensor([[1., 2.],
        [6., 8.]])

In [8]:
m1.mul(m2)

tensor([[1., 2.],
        [6., 8.]])

## Mean

In [9]:
t = torch.FloatTensor([1, 2])
t.mean()

tensor(1.5000)

In [10]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [11]:
t = torch.FloatTensor([[1, 2], [3, 4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [12]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [13]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max and Argmax

In [14]:
t

tensor([[1., 2.],
        [3., 4.]])

In [15]:
t.max()

tensor(4.)

In [16]:
print(t.max(dim=0))
print('Max   :', t.max(dim=0)[0])
print('Argmax:', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max   : tensor([3., 4.])
Argmax: tensor([1, 1])


# Lab-01-2 Tensor Manipulation 1

## view

In [17]:
import numpy as np

In [18]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]], 
              [[6, 7, 8], 
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
ft.shape

torch.Size([2, 2, 3])

In [19]:
ft.view([-1, 3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [20]:
ft.view([-1, 1, 3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

## squeeze

In [21]:
ft = torch.FloatTensor([[0], [1], [2]])
ft

tensor([[0.],
        [1.],
        [2.]])

In [22]:
ft.squeeze()

tensor([0., 1., 2.])

In [23]:
ft = torch.FloatTensor([[[0], [1], [2]]])
ft

tensor([[[0.],
         [1.],
         [2.]]])

### unsqueeze

In [24]:
ft = torch.Tensor([1, 2, 3, 4])
ft

tensor([1., 2., 3., 4.])

In [25]:
ft.unsqueeze(0)

tensor([[1., 2., 3., 4.]])

In [26]:
ft.unsqueeze(1)

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [27]:
ft.view([-1, 1])

tensor([[1.],
        [2.],
        [3.],
        [4.]])

## Type Casting

In [28]:
lt = torch.LongTensor([1, 2, 3, 4])
lt

tensor([1, 2, 3, 4])

In [29]:
lt.float()

tensor([1., 2., 3., 4.])

In [30]:
bt = torch.ByteTensor([True, False, False, True])
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [31]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate

In [32]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [33]:
torch.cat([x, y], dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [34]:
torch.cat([x, y], dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

## Stack

In [35]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [36]:
torch.stack([x, y, z], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [37]:
torch.stack([x, y, z], dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [38]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

## Ones and Zeros

In [39]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
x

tensor([[0., 1., 2.],
        [2., 1., 0.]])

In [40]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [41]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## In-place Operation

In [42]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [43]:
x.mul(2.)

tensor([[2., 4.],
        [6., 8.]])

In [44]:
x

tensor([[1., 2.],
        [3., 4.]])

In [45]:
x.mul_(2.)

tensor([[2., 4.],
        [6., 8.]])

In [46]:
x

tensor([[2., 4.],
        [6., 8.]])