# Lab-01-1 Tensor Manipulation 1

## Broadcasting

In [1]:
import torch

In [4]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [5]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]])
print(m1 + m2)

tensor([[4., 5.]])


In [6]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## Matrix Multiplication vs. (Element-wise) Multiplication

In [7]:
m1 = torch.FloatTensor([[1, 2], 
                        [3, 4]])
m2 = torch.FloatTensor([[1], 
                        [2]])

In [8]:
m1.matmul(m2)

tensor([[ 5.],
        [11.]])

In [9]:
m1 * m2

tensor([[1., 2.],
        [6., 8.]])

In [10]:
m1.mul(m2)

tensor([[1., 2.],
        [6., 8.]])

## Mean

In [11]:
t = torch.FloatTensor([1, 2])
t.mean()

tensor(1.5000)

In [12]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [14]:
t = torch.FloatTensor([[1, 2], [3, 4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [16]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [17]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max and Argmax

In [27]:
t

tensor([[1., 2.],
        [3., 4.]])

In [18]:
t.max()

tensor(4.)

In [29]:
print(t.max(dim=0))
print('Max   :', t.max(dim=0)[0])
print('Argmax:', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max   : tensor([3., 4.])
Argmax: tensor([1, 1])
