# Lab-11-1 RNN basics

In [1]:
import torch

## ※ One Hot Encoding

- "hello"

In [2]:
import numpy as np
from collections import OrderedDict

In [3]:
data = 'hello'

In [4]:
def get_chars(word):
    return ''.join(OrderedDict.fromkeys(word))

In [5]:
get_chars(data)

'helo'

In [6]:
def char2int_dict(word):
    characters = get_chars(word)
    return dict((c, i) for i, c in enumerate(characters))

In [7]:
char2int_dict(data)

{'h': 0, 'e': 1, 'l': 2, 'o': 3}

In [8]:
def int2char_dict(word):
    characters = get_chars(word)
    return dict(enumerate(characters))

In [9]:
int2char_dict(data)

{0: 'h', 1: 'e', 2: 'l', 3: 'o'}

In [10]:
def int_encode(word):
    char_to_int = char2int_dict(word)
    return np.array([[char_to_int[char] for char in word]])

In [11]:
int_encode(data)

array([[0, 1, 2, 2, 3]])

In [12]:
def one_hot_encode(word):
    arr = int_encode(word)
    n_labels = len(get_chars(word))
    
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    return torch.FloatTensor(one_hot)

In [13]:
one_hot_encode(data)

tensor([[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]])

## Data

In [14]:
input_size = 4
hidden_size = 2

h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]
input_data_np = np.array([[h, e, l, l, o], 
                          [e, o, l, l, l], 
                          [l, l, e, e, l]], dtype=np.float32)

input_data = torch.Tensor(input_data_np)

## Model

In [15]:
rnn = torch.nn.RNN(input_size, hidden_size)
outputs, _status = rnn(input_data)

# Lab-11-2 RNN hihello (and charseq)

In [16]:
data = 'hihello'

In [17]:
char_set = [char for char in get_chars(data)]
char_set

['h', 'i', 'e', 'l', 'o']

In [18]:
x_data = int_encode(data)[:, :-1]
x_data

array([[0, 1, 0, 2, 3, 3]])

In [19]:
x_one_hot = one_hot_encode(data)[:, :-1, :]
x_one_hot

tensor([[[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.]]])

In [20]:
y_data = int_encode(data)[:, 1:]
y_data

array([[1, 0, 2, 3, 3, 4]])

In [24]:
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)
print(X)
print(Y)

tensor([[[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.]]])
tensor([[1, 0, 2, 3, 3, 4]])
