In [1]:
from __future__ import print_function
import torch

## Tensors

In [2]:
x = torch.empty(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.4107, 0.2126, 0.2445],
        [0.1697, 0.2461, 0.3436],
        [0.0745, 0.5574, 0.6581],
        [0.3365, 0.2532, 0.7375],
        [0.9316, 0.2274, 0.9939]])

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.2094, -0.9343,  0.5542],
        [-0.1067, -0.5687, -0.0357],
        [ 1.6124, -1.1997, -0.1573],
        [-0.2116,  0.2057,  0.1860],
        [ 0.4542,  0.2821,  0.3118]])


In [7]:
x.size()

torch.Size([5, 3])

## Operations

In [8]:
y = torch.rand(5, 3)
x + y

tensor([[ 1.3028, -0.4102,  0.6025],
        [ 0.2088, -0.1027, -0.0341],
        [ 2.3812, -0.6022, -0.0184],
        [ 0.4822,  0.8925,  1.1527],
        [ 1.0035,  1.1180,  1.2423]])

In [9]:
torch.add(x, y)

tensor([[ 1.3028, -0.4102,  0.6025],
        [ 0.2088, -0.1027, -0.0341],
        [ 2.3812, -0.6022, -0.0184],
        [ 0.4822,  0.8925,  1.1527],
        [ 1.0035,  1.1180,  1.2423]])

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 1.3028, -0.4102,  0.6025],
        [ 0.2088, -0.1027, -0.0341],
        [ 2.3812, -0.6022, -0.0184],
        [ 0.4822,  0.8925,  1.1527],
        [ 1.0035,  1.1180,  1.2423]])

### _: inplace

In [11]:
y.add_(x)
y

tensor([[ 1.3028, -0.4102,  0.6025],
        [ 0.2088, -0.1027, -0.0341],
        [ 2.3812, -0.6022, -0.0184],
        [ 0.4822,  0.8925,  1.1527],
        [ 1.0035,  1.1180,  1.2423]])

### NumPy-like Indexing

In [12]:
x[:, 1]

tensor([-0.9343, -0.5687, -1.1997,  0.2057,  0.2821])

### .view()

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
print(y)
print(y.size())

tensor([ 0.2789,  2.7677,  1.3709, -0.9659,  1.2038,  0.4690, -1.9924, -0.5722,
         0.0344,  0.7322,  0.9183,  0.6836,  0.3714,  0.9341,  1.4032, -0.3248])
torch.Size([16])


In [14]:
z = x.view(-1, 8)
print(z)
print(z.size())

tensor([[ 0.2789,  2.7677,  1.3709, -0.9659,  1.2038,  0.4690, -1.9924, -0.5722],
        [ 0.0344,  0.7322,  0.9183,  0.6836,  0.3714,  0.9341,  1.4032, -0.3248]])
torch.Size([2, 8])


### .item() : to a scala

In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2906])
-0.2905748188495636


## NumPy Bridge

In [16]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [17]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## NumPy to Torch Tensor

In [19]:
import numpy as np

In [20]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
